In [73]:
import numpy as np
import matplotlib.pyplot as mt
import scipy.sparse as sp

N=2

#Matrices de Pauli en un hueco
sx=sp.coo_matrix(([1,1], ([0,1], [1,0])), shape=(2, 2))
sy=sp.coo_matrix(([1j,-1j], ([0,1], [1,0])), shape=(2, 2))
sz=sp.coo_matrix(([1,-1], ([0,1], [0,1])), shape=(2, 2))

I = sp.eye(N) #Identidad en subespacio del hueco
cero=sp.coo_matrix((2, 1))

fund=sp.coo_matrix(([1], ([0], [0])), shape=(2*N, 1))
exc=sp.coo_matrix(([1], ([1], [0])), shape=(2*N, 1))

#Crear hamiltoniano a mano con dos primeros terminos y sacar autovalores 
Hdiag=[]
i=0
while i<2*N:
    Hdiag.append((-1)**i)
    i+=1
H=sp.diags(Hdiag, shape=(2*N, 2*N), format='csr')
#print(H.toarray())
print((sp.kron(I,sz)).toarray())
print((sp.kron((sp.kron(I,sz)),I)).toarray())
#Implementar autovalores
    
    

[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]


In [70]:
#Idea aparcada para crear un operador como porductos tensoriales

def szi(i):
    if i==1:
        m=1
        s=sz
        while m <N:
            s=sp.kron(I,s)
            m+=1
    else:
        m=2
        s=I
        while m <N:
            if m==i:
                s=sp.kron(s,sz)
            else:
                s=sp.kron(s,I)
            m+=1
    return s
print(szi(1).toarray())

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.